### ISSUE TITLE
Issue with Fireball

### ISSUE THREAD

**Issue by Halfbite** [Holic75/SolastaModHelpers#3]
Was running multiple mods at the time, but I was able to turn everything off and found that it originates with this mod or a combination of this mod and Bard. 

Whenever any class casts Fireball the unit locks up, unable to see any UI elements after casting and unable to hotkey to end the rest of the turn. In free roam the character locks up, being unable to move or cast anymore spells.

**Comment by Holic75** [comment]
I am unable to reproduce the issue the way it is described.
Just tried to cast fireball, and did not get any issues.
