### ISSUE TITLE
InvalidOperationException: Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by K-Dark** [Holic75/SolastaModHelpers#7]
Hey there!
The line
`ServiceRepository.GetService<IPlayerControllerService>()?.ActivePlayerController?.RecomputeControlledCharacters();`
seems to be causing exceptions when selecting multiple characters through
`GameLocationSelectionManager.SelectMultipleCharacters`
(as it often called with ActivePlayerController.ControlledCharacters, recomputing it mid selection could cause this).
Cheers!

**Comment by Holic75** [comment]
Unable to reproduce
